GroceryStore/Controllers/GroceryProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GroceryStore.Data;
using GroceryStore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GroceryStore.Controllers
{
    public class GroceryProductsController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public GroceryProductsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this._context = context;
            this._userManager = userManager;
        }

        public async Task<IActionResult> Index(string category)
        {
            if (await _context.GroceryProduct.CountAsync() == 0)
            {
                List<GroceryProductsModel> Produce = new List<GroceryProductsModel>();
                Produce.Add(new GroceryProductsModel { Name = "Tomato", ImagePath = "./images/tomato.jpg", Description = "", Price = 20.99m, DateCreated = DateTime.Now, DateLastModified = DateTime.Now });
                _context.Categories.Add(new CategoryModel { Name = "Produce", GroceryProduct = Produce });

                List<GroceryProductsModel> Meat = new List<GroceryProductsModel>();
                Meat.Add(new GroceryProductsModel { Name = "Ground Beef", ImagePath = "./images/tomato.jpg", Description = "", Price = 19.99m, DateCreated = DateTime.Now, DateLastModified = DateTime.Now });
                _context.Categories.Add(new CategoryModel { Name = "Meat", GroceryProduct = Meat });

                List<GroceryProductsModel> Seafood = new List<GroceryProductsModel>();
                Seafood.Add(new GroceryProductsModel { Name = "Seafood", ImagePath = "./images/tomato.jpg", Description = "", Price = 18.99m, DateCreated = DateTime.Now, DateLastModified = DateTime.Now });
                _context.Categories.Add(new CategoryModel { Name = "Seafood", GroceryProduct = Seafood });

                await _context.SaveChangesAsync();
            }

            ViewBag.selectedCategory = category;
            List<GroceryProductsModel> model;
            if (string.IsNullOrEmpty(category))
            {
                model = await this._context.GroceryProduct.ToListAsync();
            }
            else
            {
                model = await this._context.GroceryProduct.Where(x => x.GroceryCategoryName == category).ToListAsync();
            }

            ViewData["Categories"] = await this._context.Categories.Select(x => x.Name).ToArrayAsync();

            
            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            GroceryProductsModel model = await _context.GroceryProduct.FindAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Details(int? id, int quantity, string category, string name, decimal price)
        {
            GroceryProductCart cart = null;
            if (User.Identity.IsAuthenticated)
            {
                var currentUser = await _userManager.GetUserAsync(User);
                cart = await _context.GroceryProductCart.Include(x => x.GroceryCartProducts).FirstOrDefaultAsync(x => x.ApplicationUserID == currentUser.Id);
                if (cart == null)
                {
                    cart = new GroceryProductCart();
                    cart.ApplicationUserID = currentUser.Id;
                    cart.DateCreated = DateTime.Now;
                    cart.DateLastModified = DateTime.Now;
                    _context.GroceryProductCart.Add(cart);
                }
            }
            else
            {
                if (Request.Cookies.ContainsKey("cart_id"))
                {
                    int existingCartID = int.Parse(Request.Cookies["cart_id"]);
                    cart = await _context.GroceryProductCart.Include(x => x.GroceryCartProducts).FirstOrDefaultAsync(x => x.ID == existingCartID);
                }

                if (cart == null)
                {
                    cart = new GroceryProductCart
                    {
                        DateCreated = DateTime.Now,
                        DateLastModified = DateTime.Now
                    };

                    _context.GroceryProductCart.Add(cart);
                }
            }

            GroceryCartProduct product = cart.GroceryCartProducts.FirstOrDefault(x => x.GroceryProductID == id);
            if (product == null)
            {
                product = new GroceryCartProduct
                {
                    DateCreated = DateTime.Now,
                    DateLastModified = DateTime.Now,
                    GroceryProductID = id ?? 0,
                    Quantity = 0,
                    Name = name,
                    Price = price
                };

                cart.GroceryCartProducts.Add(product);
            }
            product.Quantity += quantity;
            product.DateLastModified = DateTime.Now;

            await _context.SaveChangesAsync();


            if (!User.Identity.IsAuthenticated)
            {
                Response.Cookies.Append("cart_id", cart.ID.ToString(), new Microsoft.AspNetCore.Http.CookieOptions
                {
                    Expires = DateTime.Now.AddYears(1)
                });
            }

            return RedirectToAction("Index", "GroceryCart");
        }

        public IActionResult Produce()
        {
            return View();
        }

        public IActionResult Seafood()
        {
            return View();
        }

        public IActionResult Meat()
        {
            return View();
        }

        public IActionResult Bread()
        {
            return View();
        }

        public IActionResult Deli()
        {
            return View();
        }

        public IActionResult Beverages()
        {
            return View();
        }

        public IActionResult AlcoholicBeverages()
        {
            return View();
        }
    }
}

GroceryStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body class="w3-content" style="max-width:1200px">
    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
        <div class="w3-container w3-display-container w3-padding-16">
            <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
            <h3 class="w3-wide">
                <b>
                    <a asp-controller="Home" asp-action="Index">Store</a>
                </b>
            </h3>
        </div>
        <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
            <a asp-controller="GroceryProducts" asp-action="Index" class="w3-bar-item w3-button">All Products</a>
            <a asp-controller="GroceryProducts" asp-action="Produce" class="w3-bar-item w3-button">Produce</a>
            <a asp-controller="GroceryProducts" asp-action="Meat" class="w3-bar-item w3-button">Meat</a>
            <a asp-controller="GroceryProducts" asp-action="Seafood" class="w3-bar-item w3-button">Seafood</a>
            <a asp-controller="GroceryProducts" asp-action="Deli" class="w3-bar-item w3-button">Deli</a>
            <a asp-controller="GroceryProducts" asp-action="Bread" class="w3-bar-item w3-button">Bread & Bakery</a>
            <a asp-controller="GroceryProducts" asp-action="Beverages" class="w3-bar-item w3-button">Beverages</a>
            <a asp-controller="GroceryProducts" asp-action="AlcoholicBeverages" class="w3-bar-item w3-button">Alcoholic Beverages</a>
        </div>
        <a asp-controller="Home" asp-action="Contact" class="w3-bar-item w3-button w3-padding">Contact</a>
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding" onclick="document.getElementById('newsletter').style.display='block'">Newsletter</a>
        <a asp-controller="Home" asp-action="Subscribe" class="w3-bar-item w3-button">Subscribe</a>
    </nav>
    <!-- Top menu on small screens -->
    <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
        <div class="w3-bar-item w3-padding-24 w3-wide">Store</div>
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    </header>
    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">
        <!-- Push down content on small screens -->
        <div class="w3-hide-large" style="margin-top:83px"></div>
        @RenderBody()
    </div>
    <!-- Newsletter Modal -->
    <div id="newsletter" class="w3-modal">
        <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
            <div class="w3-container w3-white w3-center">
                <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
                <h2 class="w3-wide">NEWSLETTER</h2>
                <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
                <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
                <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
            </div>
        </div>
    </div>
    <script>
        // Accordion
        function myAccFunc() {
            var x = document.getElementById("demoAcc");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }
        // Click on the "Jeans" link on page load to open the accordion for demo purposes
        document.getElementById("myBtn").click();
        // Script to open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>